/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = new useGLTF('/kick.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Armature" position={[0, -2.9, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.036, 0.036, 0.036]}>  {/* To change the position and orientation of the bot */}
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
          geometry={nodes.Beta_Joints.geometry}
          material={materials.Beta_Joints_MAT}
          skeleton={nodes.Beta_Joints.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Beta_Surface.geometry}
          material={materials['asdf1:Beta_HighLimbsGeoSG2']}
          skeleton={nodes.Beta_Surface.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/kick.glb')